-- 부서테이블의 모든 부서 정보를 조회하기
SELECT * FROM DEPARTMENTS;

-- * 테이블의 모든 정보를 조회한다고 하더라도 아래와 같이 적어서 컬럼명을 정확하게 명시하자. *은 쓰지 말 것!
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID
FROM DEPARTMENTS;

-- 부서테이블에서 위치아이디가 1700번이 아닌 부서 정보 조회하기
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID
FROM DEPARTMENTS
WHERE LOCATION_ID != 1700; -- 오라클 쿼리에서는 != 대신 <> 으로 적을 수 있다.

-- 100사원이 관리하는 부서정보 조회하기
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID
FROM DEPARTMENTS
WHERE MANAGER_ID = 100;

-- 부서명이 'IT'인 부서의 정보 조회하기
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID
FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'IT';

-- 위치아이디가 1700번인 지역의 주소, 우편번호, 도시명, 국가코드를 조회하기
SELECT STREET_ADDRESS, POSTAL_CODE, CITY, COUNTRY_ID
FROM LOCATIONS
WHERE LOCATION_ID = 1700;

-- 최소급여가 2000이상 5000이하인 직종의 직종아이디, 직종제목, 최소급여, 최대급여 조회하기
SELECT JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY
FROM JOBS
WHERE MIN_SALARY BETWEEN 2000 AND 5000;

-- 최대급여가 20000을 초과하는 직종의 아이디, 직종제목, 최소급여, 최대급여 조회하기
SELECT JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY
FROM JOBS
WHERE MAX_SALARY > 20000;

-- 100직원에게 보고하는 사원의 아이디, 이름, 부서아이디을 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE MANAGER_ID = 100;

-- 80번 부서에서 근무하고 급여를 8000 이상 받는 사원의 아이디, 이름, 급여, 커미션포인트 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80
AND SALARY >= 8000;

-- 직종이 SA_REP이고, 커미션포인트가 0.25이상인 사원의 아이디, 이름, 급여, 커미션포인트를 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE JOB_ID = 'SA_REP' 
AND COMMISSION_PCT >= 0.25;

-- 80번 부서에 근무하고, 급여가 7000이상이고, 커미션을 받는 사원의 아이디, 이름, 급여, 연봉을 조회하기
-- 연봉 = (급여 + 급여x커미션)x12다
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, (SALARY+SALARY*COMMISSION_PCT)*12 ANNUAL_SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80
AND SALARY >= 7000
AND COMMISSION_PCT IS NOT NULL;

-- 80번 부서에 근무하고, 147번 직원에게 보고하는 사원 중에서 커미션이 0.1인 사원의 사원아이디, 이름, 직종, 급여, 커미션포인트를 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80
AND MANAGER_ID = 147
AND COMMISSION_PCT = 0.1;

-- 사원들이 수행하는 직종을 중복없이 조회하기
SELECT DISTINCT JOB_ID
FROM EMPLOYEES;

-- 사원들이 소속된 부서아이디를 모두 조회하기
SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL;